// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebShopData.Models
{
    public partial class ChiTietDonHang
    {
        public long IdCtdh { get; set; }
        public long IdDonHang { get; set; }
        public long IdCtsp { get; set; }
        public long Gia { get; set; }
        public int SoLuong { get; set; }

        public virtual ChiTietSanPham IdCtspNavigation { get; set; }
        public virtual DonHang IdDonHangNavigation { get; set; }
    }
}