// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebShopData.Models
{
    public partial class ChiTietSanPham
    {
        public ChiTietSanPham()
        {
            ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }

        public long IdCtsp { get; set; }
        public long IdSanPham { get; set; }
        public long IdSize { get; set; }
        public long IdMauSac { get; set; }
        public string ImageUrl { get; set; }
        [Required]
        public int SoLuong { get; set; }

        public virtual MauSac IdMauSacNavigation { get; set; }
        public virtual SanPham IdSanPhamNavigation { get; set; }
        public virtual Size IdSizeNavigation { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
    }
}