// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebShopData.Models
{
    public partial class DonHang
    {
        public DonHang()
        {
            ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }

        public long IdDonHang { get; set; }
        [Required]
        public long IdKhachHang { get; set; }
        [Required]
        public DateTime NgayDatHang { get; set; }
        [Required]
        public string DiaChi { get; set; }
        [Required][Phone]
        public string Sdt { get; set; }
        [Required]
        public bool TrangThai { get; set; }
        [Required]
        public long TongTien { get; set; }

        public virtual KhachHang IdKhachHangNavigation { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
    }
}