// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebShopData.Models
{
    public partial class MauSac
    {
        public MauSac()
        {
            ChiTietSanPham = new HashSet<ChiTietSanPham>();
        }

        public long IdMauSac { get; set; }
        public string TenMauSac { get; set; }

        public virtual ICollection<ChiTietSanPham> ChiTietSanPham { get; set; }
    }
}