// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebShopData.Models
{
    public partial class SanPham
    {
        public SanPham()
        {
            ChiTietSanPham = new HashSet<ChiTietSanPham>();
        }

        public long IdSanPham { get; set; }
        public string TenSp { get; set; }
        public long IdTheLoai { get; set; }
        public string Image { get; set; }
        public long GiaNhap { get; set; }
        public long GiaBan { get; set; }
        public long GiamGia { get; set; }
        public DateTime NgayTao { get; set; }

        public virtual TheLoai IdTheLoaiNavigation { get; set; }
        public virtual ICollection<ChiTietSanPham> ChiTietSanPham { get; set; }
    }
}