// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebShopData.Models
{
    public partial class ViewCtsanPham
    {
        public long IdCtsp { get; set; }
        public long IdSanPham { get; set; }
        public string TenSp { get; set; }
        public long IdSize { get; set; }
        public string TenSize { get; set; }
        public long IdMauSac { get; set; }
        public string TenMauSac { get; set; }
        public string ImageUrl { get; set; }
        public int SoLuong { get; set; }
    }
}