// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebShopData.Models
{
    public partial class ViewSanPham
    {
        public long IdSanPham { get; set; }
        public string TenSp { get; set; }
        public long IdTheLoai { get; set; }
        public string TenTheLoai { get; set; }
        public string Image { get; set; }
        public long GiaNhap { get; set; }
        public long GiaBan { get; set; }
        public long GiamGia { get; set; }
        public DateTime NgayTao { get; set; }
        public int? SoLuong { get; set; }
    }
}