// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebShopData.Models
{
    public partial class ViewSanPhamBanChay
    {
        public string TenSp { get; set; }
        public DateTime NgayDatHang { get; set; }
        public int? SoLuongBan { get; set; }
    }
}