// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebShopData.Models
{
    public partial class ViewDoanhThu
    {
        public long IdDonHang { get; set; }
        public DateTime NgayDatHang { get; set; }
        public long? TongTien { get; set; }
    }
}